version = 1

[approve]
# note: remove the "[bot]" suffix from GitHub Bot usernames.
# Instead of "dependabot[bot]" use "dependabot".
auto_approve_usernames = ["dependabot"]

# if using `update.always`, add dependabot to `update.ignore_usernames` to allow
# dependabot to update and close stale dependency upgrades.
[update]
ignored_usernames = ["dependabot"]

[merge.message]
# use title of PR for merge commit.
title = "pull_request_title" # default: "github_default"

# use body of PR for merge commit.
body = "pull_request_body" # default: "github_default"

# add the PR number to the merge commit title, like GitHub.
include_pr_number = true # default: true

# use the default markdown content of the PR for the merge commit.
body_type = "markdown" # default: "markdown"

# remove html comments to auto remove PR templates.
strip_html_comments = true # default: false
